## Casting list into an array

In [8]:
import numpy as np

my_list = [1,2,3]
my_matrix = [my_list]*3

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Initializing arrays/matrices using numpy

Arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])