## Casting list into an array

In [8]:
import numpy as np

my_list = [1,2,3]
my_matrix = [my_list]*3

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Initializing arrays/matrices using numpy

### Arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Other ways of initializing

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.linspace(0,10,10) #100 evenly spaced elements in a 1d array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])