## Casting list into an array

In [8]:
import numpy as np

my_list = [1,2,3]
my_matrix = [my_list]*3

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Initializing arrays/matrices using numpy

### Arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Other ways of initializing

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.linspace(0,10,10) #100 evenly spaced elements in a 1d array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### Creating an identity matrix

In [25]:
np.eye(4) #number of rows it the same as number of columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Initializing using random

#### From a uniform distribution

In [30]:
np.random.rand(5)

array([0.52953439, 0.45198096, 0.75530658, 0.06538251, 0.75523209])

In [31]:
np.random.rand(5,5)

array([[0.35271198, 0.3727463 , 0.98626367, 0.47405684, 0.04896269],
       [0.74660509, 0.74498284, 0.98055605, 0.01794334, 0.1682935 ],
       [0.1741595 , 0.80291901, 0.35870869, 0.78469163, 0.65679129],
       [0.97971752, 0.63423939, 0.93447718, 0.88119223, 0.20489663],
       [0.80023199, 0.86973262, 0.18944793, 0.09844106, 0.5831308 ]])

#### Using a gaussian/normal distribution

In [33]:
np.random.randn(5,5)

array([[ 0.40263709, -0.07076415, -1.13399744, -1.10268196, -1.06284657],
       [-0.4840652 ,  0.63464289,  1.57043829, -0.55122032, -1.77745529],
       [ 0.31259797, -1.53450685, -0.02949588, -0.63751918,  1.17882136],
       [ 0.08910091, -0.59328095, -0.12677958,  1.04986065,  1.60815142],
       [-1.00945937, -2.07985091, -0.74482785,  0.83164211,  0.80095841]])

#### Random Integers

In [36]:
np.random.randint(1,100,10)

array([18, 81, 37, 59,  1,  4, 70, 75, 84, 76])

## Useful Array.Methods

In [37]:
arr = np.random.randint(1,100,10)

### Reshape

In [40]:
arr.reshape(5,2) #rows x columns should be = len(arr)

array([[47, 11],
       [15, 76],
       [38, 49],
       [70, 23],
       [91, 52]])

### Max and Min

In [43]:
arr

array([47, 11, 15, 76, 38, 49, 70, 23, 91, 52])

In [44]:
arr.max()

91

In [45]:
arr.min()

11

In [46]:
arr.argmax()

8

In [47]:
arr.argmin()

1

### Shape

In [51]:
print(arr.shape)
arr.reshape(5,2).shape

(10,)


(5, 2)

### Data Type in Array

In [52]:
arr.dtype

dtype('int64')

## Indexing and Selection

In [54]:
arr

array([47, 11, 15, 76, 38, 49, 70, 23, 91, 52])

In [53]:
arr[0]

47

In [55]:
arr[0:3]

array([47, 11, 15])

### Numpy copies by reference and not deep copy

In [57]:
arr

array([47, 11, 15, 76, 38, 49, 70, 23, 91, 52])

In [58]:
slice_of_array = arr[0:3]
slice_of_array[:] = 99
arr

array([99, 99, 99, 76, 38, 49, 70, 23, 91, 52])

### Deep Copying a np array

In [82]:
arr_copy = arr.copy()
arr_copy[:] = 10000
arr, arr_copy

(array([[-1.18121772,  0.01824759, -0.48330011, -0.67441614, -0.60919709],
        [-1.28169961, -1.18522841, -1.04360701, -0.72049407,  0.37476799]]),
 array([[10000., 10000., 10000., 10000., 10000.],
        [10000., 10000., 10000., 10000., 10000.]]))

### Indexing

In [91]:
arr = np.random.randn(1, 15)
arr = arr.reshape(3,5)


In [92]:
arr

array([[-1.03088142, -0.69463837, -1.48801444,  0.98965135, -0.24398845],
       [-1.66753443, -0.06946964,  1.44879355, -1.14500945, -1.13117646],
       [-0.62810417, -0.58441046, -0.78080749, -0.26865046, -1.39992981]])

In [93]:
arr[1]

array([-1.66753443, -0.06946964,  1.44879355, -1.14500945, -1.13117646])

In [94]:
arr[1,0]

-1.6675344325253219

In [95]:
arr[1][0]

-1.6675344325253219

## Grabbing submatrix

In [98]:
arr[:2, 1:]

array([[-0.69463837, -1.48801444,  0.98965135, -0.24398845],
       [-0.06946964,  1.44879355, -1.14500945, -1.13117646]])

### Conditionals

In [100]:
arr = np.random.randint(1,11,10)
arr

array([ 4,  5,  6,  2,  9,  3, 10,  8,  2,  6])

In [102]:
bool_arr = arr>5
bool_arr

array([False, False,  True, False,  True, False,  True,  True, False,
        True])

#### Conditional Selection

In [103]:
arr[arr>5]

array([ 6,  9, 10,  8,  6])